version: "2"

run:
  build-tags:
    - integration_test

linters:
  disable:
    - tagliatelle
    - wsl
    - exhaustruct
    - lll
    - varnamelen
    - nlreturn
    - err113
    - wrapcheck
    - testpackage
    - nolintlint
    - depguard
    - ireturn
    - perfsprint
    - musttag
    - tagalign
    - mnd
    - canonicalheader
    - intrange
    - testifylint
    - paralleltest
    - nonamedreturns
    - dupword
    - gochecknoglobals
    - gosmopolitan
  settings:
    cyclop:
      max-complexity: 12
    funlen:
      lines: 90
    errcheck:
      # errcheck -verbose .
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (*github.com/anthropics/anthropic-sdk-go/packages/ssestream.Stream[github.com/anthropics/anthropic-sdk-go.MessageStreamEventUnion]).Close
        - (*github.com/sashabaranov/go-openai.streamReader[github.com/sashabaranov/go-openai.ChatCompletionStreamResponse]).Close
    goheader:
      values:
        regexp:
          fromyear: \d\d\d\d
      template: |-
        SPDX-FileCopyrightText: {{ FROMYEAR }} Masa Cento
        SPDX-License-Identifier: MIT

exclusions:
  rules:
    - path: _test\.go
      linters:
        - gocognit
        - nestif
        - cyclop
    - path: examples/
      linters:
        - forbidigo
        - goheader
